### ISSUE TITLE
create contact page

### ISSUE THREAD

**Issue by DenSonmez** [De-4-Data-Amigos/Portfolio-template-creator#117]

**Comment by ConfuzzedCat** [comment]
The Contact page, should use a contact form component, which takes an email, maybe a name and a message/question as input fields, and an apiurl as parameter for the component.
The component needs to use the api url given to it, to send the inputs (email, name(optional) and message) to the backend.
The backend, needs to save the data in the database.
(out of scope) The saved contact message will need to be sent to own of the api as email, using smtp.

![Image](https://github.com/user-attachments/assets/4697a425-e537-45b0-90d5-0efa5108e908)
